version: '3.6'

services:
  mongodb-server:
    image: mongo:latest
    container_name: mongodb-server-container
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    networks:
      - my-network

volumes:
  mongodb:
  mongoconfig:

networks:
  my-network:
    driver: bridge
