version: "3"
services:
  mysql-service:
    image: mysql:8.0.16
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    container_name: mysql-service-container
    ports:
      - 7308:3306
    networks:
      - my-network

volumes:
  mysql_data:
    driver: local

networks:
  my-network:
    driver: bridge
